DevCard-MVC/Models/Article.cs
namespace DevCard_MVC.Models
{
	public class Article
	{
		public long Id { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
        public string Image { get; set; }

        public Article(long id, string title, string description, string image)
        {
            Id = id;
			Title = title;
			Description = description;
			Image = image;
        }
	}
}

DevCard-MVC/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace DevCard_MVC.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3,ErrorMessage = "حداقل طول این فیلد 3 کاراکتر است")]
        [MaxLength(100,ErrorMessage = "حداکثر طول این فیلد 100 کاراکتر است")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "ایمیل به صورت صحیح وارد نشده است")]
        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string Email { get; set; }

        public string Service { get; set; }

        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string Message { get; set; }
    }
}

DevCard-MVC/Models/ErrorViewModel.cs
using System;

namespace DevCard_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard-MVC/Models/Project.cs
namespace DevCard_MVC.Models
{
	public class Project
	{
		public long Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
        public string Image { get; set; }
		public string Client { get; set; }

		public Project(long id , string name , string description ,string image, string client)
		{
			Id = id;
			Name = name;
			Description = description;
			Image = image;
			Client = client;
		}
	}
}

DevCard-MVC/Controllers/HomeController.cs
using System;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace DevCard_MVC.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            var model = new Contact();
            return View(model);
        }

        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    var name = form["name"];
        //    var email = form["email"];
        //    var service = form["service"];
        //    var message= form["message"];
        //    return Json(Ok());
        //}
        [HttpPost]
        public JsonResult Contact(Contact form)
        {
            Console.WriteLine(form);
            return Json(Ok());
        }

        [ResponseCache(Duration = 0 , Location = ResponseCacheLocation.None , NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCard-MVC/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.Controllers
{
    public class TestController : Controller
    {
        //public ContentResult Index()
        //{
        //    return Content(@"<h1 style ='color:red;' > Hello I`m Mohammad Fallahi</h1>" , "text/html");
        //}
        //public FileResult Index()
        //{
        //    var fileByte = System.IO.File.ReadAllBytes("wwwroot/Files/Robots.txt");
        //    return File(fileByte, "text/html", "Robots.txt");
        //}
        //public JsonResult Index()
        //{
        //    return Json(new
        //    {
        //        id = 1,
        //        name = "mohammad",
        //        job="Programmer",
        //        age =25,
        //        telegramId = "mdblackk1999"
        //    });
        //}

        // ----- this method reWrite by Class JavaScript ------
        //public JavaScriptResult Index()
        //{
        //    return new JavaScriptResult("setTimeout(function(){alert(\"This is Delayed Message by Js\"); },1500)");
        //}
        //public IActionResult Index()
        //{
        //        //return new OkResult();
        //        //return new StatusCodeResult(503);
        //        //return new NoContentResult();
        //    return new NotFoundResult();
        //}
        //public RedirectToActionResult Index()
        //{
        //    return RedirectToAction("Contact", "Home");
        //}
    }

    //------  this secction for JvaScriptResult --------
    //public class JavaScriptResult : ContentResult
    //{
    //    public JavaScriptResult(string data)
    //    {
    //        Content = data;
    //        ContentType = "application/Javascript";
    //    }
    //}
}

DevCard-MVC/ViewComponents/LatestArticlesViewComponent.cs
using System.Collections.Generic;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var article = new List<Article>
            {
                new Article(1,"آموزش طراحی سایت حرفه ای و پیشرفته","کامل ترین دوره طراحی سایت و ورود به بازار کار با Asp.Net Core MVC","blog-post-thumb-card-1.jpg"),
                new Article(2,"آموزش جامع javaScript","تنها دوره جامع و فارسی زبان آموزش JavaScript مقدماتی و پیشرفته تا ورود به بازار کار","blog-post-thumb-card-2.jpg"),
                new Article(3,"آموزش Html و css حرفه ای","کامل ترین دوره طراحی سایت و ورود به بازار کار با Html,Css","blog-post-thumb-card-3.jpg"),
                new Article(4,"آموزش زبان برنامه نویسی C# مقدماتی","دوره مقدماتی سی شارپ","blog-post-thumb-card-4.jpg"),
                new Article(5,"آموزش زبان برنامه نویسی C# پیشرفته","دوره پیشرفته سی شارپ","blog-post-thumb-card-5.jpg"),
            };
            return View("_LatestArticles",article);
        }
    }
}

DevCard-MVC/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using DevCard_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_MVC.ViewComponents
{
	public class ProjectsViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			var projects = new List<Project>
			{
				new Project(1, "تاکسی اینترنتی", "درخواست آنلاین تاکسی برای سفر های درون شهری","project-1.jpg", "MDCO"),
				new Project(1, "زود فود کده", "درخواست آنلاین و سریع غذای سنتی و آماده همراه با مخلفات", "project-6.jpg","zoodFood.Co"),
				new Project(1, "قهوه  آل ایچ", "سرو و ارسال انواع قهوه و دسر و نوشیدنی های گرم و سرد","project-7.jpg", "Alleach"),
				new Project(1, "پوشاک مایا", "ارسال انواع لباس زمستانی و تابستانی مردانه و زنانه در طرح های مختلف","project-4.jpg",
                    "maya")
			};
			return View("_Projects" , projects);
		}
	}
}

DevCard-MVC/Views/Home/Components/LatestArticles/_LatestArticles.cshtml
@model List<Article>

<section class="latest-blog-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5" id="blog-section">آخرین مقالات</h2>
        <div class="row">
            @foreach (var article in Model)
            {
                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="~/assets/images/blog/@article.Image" alt="@article.Description">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="#">
                                    @article.Title
                                </a>
                            </h5>
                            <p class="card-text">
                                @article.Description
                            </p>
                            <p class="mb-0"><a class="more-link" href="#">ادامه مطلب</a></p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

DevCard-MVC/Views/Home/Components/Projects/_Projects.cshtml
@model IEnumerable<DevCard_MVC.Models.Project>


<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
        <div class="row">

            @foreach (var project in Model)
            {
                <div class="col-md-6 mb-5">
                    <div class="card project-card">
                        <div class="row no-gutters">
                            <div class="col-lg-4 card-img-holder">
                                <img src="~/assets/images/project/@project.Image" class="card-img" alt="@project.Name" title="@project.Description">
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="project.html" class="theme-link">
                                          @project.Id : @project.Name
                                        </a>
                                    </h5>
                                    <p class="card-text">
                                        @project.Description
                                    </p>
                                    <p class="card-text"><small class="text-muted">مشتری: @project.Client</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
	</div>
</section>

DevCard-MVC/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با من";
}

<section class="cta-section theme-bg-light py-5">
	<div class="container text-center single-col-max-width">
		<h2 class="heading">ارتباط با ما</h2>
		<div class="intro">
			<p>
				شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
				نوشته و ارسال کنید.
			</p>
			<p>همچنین از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
			<ul class="list-inline mb-0">
				<li class="list-inline-item mb-3">
					<a class="twitter" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>

				<li class="list-inline-item mb-3">
					<a class="linkedin" href="#">
						<i class="fab fa-linkedin-in fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="github" href="#">
						<i class="fab fa-github-alt fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="instagram" href="http://insragram.com/mohammadfl_1999">
						<i class="fab fa-instagram fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="stack-overflow" href="#">
						<i class="fab fa-stack-overflow fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="medium" href="#">
						<i class="fab fa-medium-m fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="codepen" href="#">
						<i class="fab fa-codepen fa-fw fa-lg"></i>
					</a>
				</li>
			</ul>
		</div>
		</div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
	<div class="container">
		<form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
			<h3 class="text-center mb-3">در دسترس باشید!</h3>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span asp-validation-for="Name" class="Text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
					<span asp-validation-for="Email" class="Text-danger"></span>
				</div>
				<div class="form-group col-12">
					<select class="custom-select" asp-for="Service">
						<option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
						<option value="basic">نقره ای</option>
						<option value="standard">طلایی</option>
						<option value="premium">پلاتین</option>
						<option value="not sure">الماس</option>
					</select>
				</div>
				<div class="form-group col-12">
					<label class="sr-only" asp-for="Message">پیغام شما</label>
                    <textarea class="form-control" asp-for="Service"
							  placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
					<span asp-validation-for="Message" class="Text-danger"></span>
				</div>
				<div class="form-group col-12">
					<button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
				</div>
			</div>
		</form>
	</div>
</section>

DevCard-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
	<div class="container">
		<div class="profile-teaser media flex-column flex-lg-row">
			<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/me.jpg" alt="">
			<div class="media-body">
				<h2 class="name font-weight-bold mb-1">محمد فلاحی</h2>
				<div class="tagline mb-3">درباره من :</div>
				<div class="bio mb-4">
					لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
					طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
					جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
				</div>
				<div class="mb-4">
					<a class="btn btn-primary mr-2 mb-3" href="http://t.me/mdblack_contact">
						<i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
							برو به کانال تلگرام
						</span> 
					</a>
					<a class="btn btn-secondary mb-3" href="#blog-section">
						<i class="fas fa-file-alt ml-2"></i>
						<span class="d-none d-md-inline">مشاهده </span> مشاهده مقالات
					</a>
				</div>
			</div>

		</div>
	</div>
</section>

@* loading Partial View *@

    @* <partial name="Projects"/> *@
@* @await Html.PartialAsync("Projects")*@
@* @await Html.PartialAsync("Projects",new List<Project>()) *@

@* End Loading Partial View *@



@* Loading View Component *@

@* Load Projects Section *@
@await Component.InvokeAsync("Projects")

<div class="container">
    <hr>
</div>

@* Load Articles Section *@
@await Component.InvokeAsync("LatestArticles")

@* End Loading View Component *@

DevCard-MVC/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
    <small class="copyright">
        تولید شده توسط &copy;
        <a href="https://t.me/mdblack_1999" target="_blank"> محمد فلاحی </a>
    </small>
</footer>

DevCard-MVC/Views/Shared/Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="@Url.Action("Index","Home")">محمد فلاحی</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/me-layout.png" alt="image">

                    <div class="bio mb-3">
                        با سلام محمد فلاحی هستم، برنامه نویس سی شارپو فول استک، به سایت شخصی من خوش امدید
                    </div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">
                            <i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

DevCard-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>سایت شخصی من - @ViewData["Title"]</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="favicon.ico">

	<script defer src="~/assets/fontawesome/js/all.js"></script>
	<link rel="stylesheet" href="~/assets/css/theme-1.css">
	<link rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>

	    <partial name="Header"/>

	<div class="main-wrapper">
		@RenderBody()

        
        
        <partial name="Footer"/>

	</div>

	<!-- Javascript -->
	<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
	<script src="~/assets/plugins/popper.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @* <script src="@Url.Action("Index","Test")"></script> *@
</body>

</html>